import asyncio
import html
import logging
import random
import re
import httpx
from app.config import settings

log = logging.getLogger(__name__)


class TelegramPublisher:
    @property
    def configured(self) -> bool:
        return bool(settings.telegram_bot_token and settings.telegram_target_chat)

    async def _call(self, method: str, payload: dict) -> dict:
        if not settings.telegram_bot_token:
            raise RuntimeError('TELEGRAM_BOT_TOKEN não configurado')
        url = f'https://api.telegram.org/bot{settings.telegram_bot_token}/{method}'
        last = None
        attempts = 1 if method in {'sendPhoto', 'sendMessage'} else max(1, settings.http_max_retries)
        for attempt in range(attempts):
            try:
                async with httpx.AsyncClient(timeout=25.0) as client:
                    r = await client.post(url, json=payload)
                try:
                    data = r.json()
                except Exception:
                    raise RuntimeError(f'Telegram HTTP {r.status_code}: {r.text[:500]}')
                if data.get('ok'):
                    return data['result']
                retry_after = ((data.get('parameters') or {}).get('retry_after'))
                if retry_after and attempt + 1 < attempts:
                    await asyncio.sleep(min(int(retry_after), 60))
                    continue
                raise RuntimeError(str(data))
            except Exception as exc:
                last = exc
                if attempt + 1 >= attempts:
                    break
                await asyncio.sleep((2 ** attempt) + random.random())
        raise RuntimeError(str(last))

    async def get_me(self) -> dict:
        return await self._call('getMe', {})

    async def get_target_chat(self) -> dict:
        if not settings.telegram_target_chat:
            raise RuntimeError('TELEGRAM_TARGET_CHAT não configurado')
        return await self._call('getChat', {'chat_id': settings.telegram_target_chat})

    @staticmethod
    def _plain_text(text: str) -> str:
        # Captions generated by this project use only b/s tags. This is a safe fallback if
        # Telegram rejects HTML parsing for any unexpected reason.
        return html.unescape(re.sub(r'</?(?:b|s)>', '', text or '', flags=re.I))

    async def publish(self, caption: str, affiliate_url: str, image_url: str | None = None) -> dict:
        if not self.configured:
            raise RuntimeError('TELEGRAM_BOT_TOKEN/TELEGRAM_TARGET_CHAT não configurados')
        keyboard = {'inline_keyboard': [[{'text': '🛒 COMPRAR NA SHOPEE', 'url': affiliate_url}]]}
        if image_url:
            return await self._call('sendPhoto', {
                'chat_id': settings.telegram_target_chat, 'photo': image_url,
                'caption': caption[:1024], 'parse_mode': 'HTML', 'reply_markup': keyboard})
        return await self._call('sendMessage', {
            'chat_id': settings.telegram_target_chat, 'text': caption[:4096],
            'parse_mode': 'HTML', 'reply_markup': keyboard,
            'link_preview_options': {'is_disabled': False}})

    async def notify_admin(self, text: str):
        if not settings.telegram_admin_chat or not settings.telegram_bot_token:
            return
        try:
            await self._call('sendMessage', {
                'chat_id': settings.telegram_admin_chat,
                'text': text[:4000],
                'disable_notification': True,
            })
        except Exception:
            log.exception('Falha ao enviar alerta administrativo')
